# Generated by Django 5.2.11 on 2026-02-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='weighted_score',
            field=models.FloatField(default=0.0),
        ),
    ]
