# Generated by Django 5.2.12 on 2026-03-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_testattempt_weighted_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='mark',
            field=models.BooleanField(default=False),
        ),
    ]
