# Generated by Django 5.2.12 on 2026-03-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('theme', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
    ]
